# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: localhost

development:
  <<: *default
  database: decision_backend_development

test:
  <<: *default
  database: decision_backend_test

production:
  <<: *default
  database: decision_backend_production
  username: decision_backend
  password: <%= ENV["DECISION_BACKEND_DATABASE_PASSWORD"] %>
